# Generated by Django 4.2.5 on 2023-10-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
