# Generated by Django 4.2.5 on 2023-10-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_contact_alter_post_options_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalNewsPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portals.post')),
            ],
            bases=('portals.post',),
        ),
        migrations.CreateModel(
            name='PoliticalNewsPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portals.post')),
            ],
            bases=('portals.post',),
        ),
        migrations.CreateModel(
            name='ScienceNewsPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portals.post')),
            ],
            bases=('portals.post',),
        ),
        migrations.CreateModel(
            name='SportsNewsPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portals.post')),
            ],
            bases=('portals.post',),
        ),
    ]
