# Generated by Django 4.2.5 on 2023-10-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_internationalnewspost_politicalnewspost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNewsPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portals.post')),
            ],
            bases=('portals.post',),
        ),
    ]
